### ISSUE TITLE
Realtime discussion medium required [IRC]

### ISSUE THREAD

**Issue by debloper** [mozilla/process-releases#7]
It may seem to be a bit obsolete - but an IRC is still pretty good for quick questions etc. & it wouldn't hurt anyway. Not sure whether we already have a moznet-channel (couldn't find one though), it should be created if necessary.

It also has to be announced in the index page.

**Comment by LegNeato** [comment]
we always idle in assorted channels on irc.mozilla.org...are you asking for a specific channel related to these docs?

**Comment by debloper** [comment]
Yeah, I am. #relplan perhaps, (cause #process-releases is quite a long name) as per the current convension.

Actually, I also want to propose a renovation in moznet IRC. But, not sure how to make the correct person to know (even then, make 'em hear - cuz I'm apparantly new).

The channels as of now, are created based on a topic, rather than the purpose. This helps in general chatting IRCs, but not in this kind of diverse and (mostly) query/support-channels.

## Example

Say for example, #extdev, #amo, #addons, each channel has individual purposes, but all have a primary objective of helping outsiders (and sometimes as an alternative communication of the regular members/idlers) about Mozilla addons.
- People coming with a specific problem take a while deciding - which channel his problem goes in. Or keeps knocking the wrong door & redirected (even if #addons contain 80% of the same members as #extdev/#amo).
- Just in case, his problem contains issues partly from #addons & #amo OR, #extdev & #addons - he has to hop from one channel, being answered partially & shown the way to the other one & describe it all again.
- It also leads the regular members to join an immense numbers of channels - each with very low traffic. Some prefer to join one of these channels, where he might have answered many issues of the other. Some even opts NOT to join any channel of that bunch (who could have been a potential help).
- Along with numbers of channels, there comes the duty to manage all these. An united(as in set theory) channel of these three channels' ops/h-ops combined would be more steady against flooding etc. attacks (last one happened just 3days ago).

## Workaround

If we could reorder the channels in a more efficient way - that from being topic specific, they'll be more _objective specific_ OR _tiered in layers_ (obviously leaving some high traffic channels leaving as is, like #firefox)
1. Objective Specific
   - In this case, channels will be like #addons #browser #messaging #bugs #planning etc.
2. Tiered in Layers
   - In this case, channels will be like #mozFoundation #mozCorp #Admins #Evangelists #appSupport etc.

Although, a hybrid of both of these seems more real-world, this is just a concept. It definitely has sharp edges & rough polishes - which I want to be mended by a more general discussion/decision.

This workaround can take the numbers of active channels down to 1/3rd, and giving Mozilla a strong reason to keep IRC up as a robust communication medium, than mainly for a historical reason (a nostalgia, fading day by day).

**Comment by LegNeato** [comment]
I think this is too much change unfortunately. There are other plans to tackle the opaqueness of IRC for new users but the channels have sort of grown organically over time and I don't see forcing a more rigid structure happening. Sorry, though I do appreciate the suggestion...perhaps this would be better discussed on a newsgroup like mozilla-dev-planning?
